sudo: required
services:
  - docker

before_install:
  - docker build -t privatejoker/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true privatejoker/react-test npm run test --coverage

after_success:
  - docker build -t privatejoker/multi-client ./client
  - docker build -t privatejoker/multi-nginx ./nginx
  - docker build -t privatejoker/multi-server ./server
  - docker build -t privatejoker/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push privatejoker/multi-client
  - docker push privatejoker/multi-nginx
  - docker push privatejoker/multi-server
  - docker push privatejoker/multi-worker

