sudo: required
services:
  - docker

before_install:
  - docker build -t khattri/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true khattri/react-test npm run test --coverage

after_success:
  - docker build -t khattri/multi-client ./client
  - docker build -t khattri/multi-nginx ./nginx
  - docker build -t khattri/multi-server ./server
  - docker build -t khattri/multi-worker ./worker
  # Log in to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  - docker push khattri/multi-client
  - docker push khattri/multi-nginx
  - docker push khattri/multi-server
  - docker push khattri/multi-worker

